name: Navnetic Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release version
        id: release_version
        run: |
          app_version=$(grep "APP_VERSION" version.ts | sed -ne "s/.*= '\(v[0-9]*\.[0-9]*\.[0-9]*\)'.*/\1/p")
          echo "app_version=$app_version" >> $GITHUB_ENV

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: 检查构建文件
        run: |
          ls -al .

      - name: 删除打包中不需要的文件
        run: |
          rm -f README.md
          rm -rf .git 
          rm -rf .github
          rm -f .gitignore 

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.RELEASE_TOKEN }}
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/navnetic:latest
            ${{ secrets.DOCKER_USERNAME }}/navnetic:${{ env.app_version }}
