name: build Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: 从文件获取版本号
        id: get_versionn
        run: |
          echo "app_version=$(cat version)" >> $GITHUB_ENV


      - name: 更新前端文件version.ts
        run: |
          echo "export const version = '${{ env.app_version }}';" > fronted/version.ts

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            fronted/package-lock.json

      - name: 安装@angular/cli依赖
        run: npm install -g @angular/cli

      - name: Build前端
        run: |
          cd fronted
          npm install --force
          npm run build

      - name: 检查前端构建后文件
        run: |
          ls -al fronted/dist/fronted/browser

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Build for amd64
        run: |
          cd backend
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a --trimpath -o dist/linux/amd64/Navnetic .

      - name: Build for arm64
        run: |
          cd backend
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a --trimpath -o dist/linux/arm64/Navnetic .

      - name: 检查构建后文件后端文件
        run: |
          ls -al backend/dist/linux/amd64
          ls -al backend/dist/linux/arm64


      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: 登录DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建和推送Docker镜像
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/navnetic-angular:latest
            ${{ secrets.DOCKER_USERNAME }}/navnetic-angular:${{ env.app_version }}
          push: true

